#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
echo "Setting up environment in $(pwd)"
python3.13 -m venv venv
source venv/bin/activate
#python3.13 -m pip install --requirement requirements.dev.txt